name: Test
on: [push, pull_request]
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build
      - run: npm run test
      - uses: codecov/codecov-action@v3.1.0
        with:
          files: coverage/lcov.info

  automerge:
    needs: build-lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
