name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build
      - run: npm run test
  
  automerge:
    needs: build-lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}